<?php

declare(strict_types=1);

namespace Flowd\PhirewallPresetBadIps;

/**
 * Turns a raw IP feed into the bundled `bad-ips.data` snapshot plus its manifest.
 *
 * Works on in-memory feed content so the download step stays separate and the
 * importer is testable without network or a real filesystem source.
 */
final class Importer
{
    public const DATA_FILE = 'bad-ips.data';

    public const MANIFEST_FILE = 'manifest.json';

    public function import(string $feedContent, FeedSource $feedSource, string $destinationDirectory, string $importedAt): ImportReport
    {
        $addresses = FeedParser::parse($feedContent);
        if ($addresses === []) {
            throw new \RuntimeException('The feed produced no valid IPv4 addresses.');
        }

        $this->ensureDirectory($destinationDirectory);

        $header = sprintf(
            "# Generated by flowd/phirewall-preset-bad-ips. Do not edit.\n# Source: %s (%s), level %s, %s. %d addresses imported %s.\n",
            $feedSource->name,
            $feedSource->url,
            $feedSource->level,
            $feedSource->license,
            count($addresses),
            $importedAt,
        );
        $this->writeFile($destinationDirectory, self::DATA_FILE, $header . implode("\n", $addresses) . "\n");

        $importReport = new ImportReport($feedSource, count($addresses), $importedAt);

        $manifestJson = json_encode($importReport->toManifestArray(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        if ($manifestJson === false) {
            throw new \RuntimeException('Cannot encode the import manifest as JSON.');
        }

        $this->writeFile($destinationDirectory, self::MANIFEST_FILE, $manifestJson . "\n");

        return $importReport;
    }

    private function ensureDirectory(string $directory): void
    {
        if (is_dir($directory)) {
            return;
        }

        if (!mkdir($directory, 0o775, true) && !is_dir($directory)) {
            throw new \RuntimeException('Cannot create destination directory: ' . $directory);
        }
    }

    private function writeFile(string $directory, string $fileName, string $content): void
    {
        $path = rtrim($directory, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $fileName;
        if (file_put_contents($path, $content) === false) {
            throw new \RuntimeException('Cannot write file: ' . $path);
        }
    }
}
