<?php

declare(strict_types=1);

namespace Flowd\PhirewallPresetBadIps\Tests\Unit;

use Flowd\PhirewallPresetBadIps\FeedSource;
use Flowd\PhirewallPresetBadIps\Importer;
use Flowd\PhirewallPresetBadIps\Manifest;
use org\bovigo\vfs\vfsStream;
use PHPUnit\Framework\TestCase;

final class ImporterTest extends TestCase
{
    private function source(): FeedSource
    {
        return new FeedSource('stamparm/ipsum', 'https://github.com/stamparm/ipsum', '3', 'The Unlicense (public domain)');
    }

    public function testWritesDataFileAndManifest(): void
    {
        vfsStream::setup('pkg');
        $destination = vfsStream::url('pkg/resources');

        $importReport = (new Importer())->import("203.0.113.7\n192.0.2.1\n192.0.2.1\n", $this->source(), $destination, '2026-06-13T10:00:00+00:00');

        $this->assertSame(2, $importReport->ipCount);

        $data = (string) file_get_contents($destination . '/bad-ips.data');
        $this->assertStringContainsString('# Generated by flowd/phirewall-preset-bad-ips', $data);
        $this->assertStringContainsString("192.0.2.1\n203.0.113.7\n", $data);

        $manifest = Manifest::read($destination);
        $this->assertSame('stamparm/ipsum', $manifest->feedName);
        $this->assertSame('3', $manifest->feedLevel);
        $this->assertSame(2, $manifest->ipCount);
        $this->assertSame('2026-06-13T10:00:00+00:00', $manifest->importedAt);
    }

    public function testEmptyFeedThrows(): void
    {
        vfsStream::setup('pkg');

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('no valid IPv4');

        (new Importer())->import("# nothing\n", $this->source(), vfsStream::url('pkg/resources'), '2026-06-13T10:00:00+00:00');
    }
}
